### PR TITLE
fix(systemd-networkd): make systemd-networkd a proper network provider 

### LINKED ISSUE #737: `systemd-networkd` should be a `network` service provider
Currently `dracut` contains two modules that help to setup network at init time: `network` and `systemd-networkd`. Users suppose to use only one of the modules to enable network functionality.

Some third-party modules (e.g. [clevis-pin-tang](https://github.com/latchset/clevis/blob/master/src/luks/systemd/dracut/clevis-pin-tang/module-setup.sh.in#L22)) need network and specify `network` module as a requirement. This unfortunately pulls the `network` module even on the systems that configure `systemd-networkd`.

`dracut` need to be able to specify `module A provides network functionality` so clients should not care about choosing a particular network module implementation.

### PR DESCRIPTION
**Pull request by johannbg**
Let's make systemd-networkd a proper network provider which should fix #737
Node that this PR adds dependencies on the dbus module ( since it provides networkd dbus files ) as well as sysusers ( which replaces the grep passwd section from the existing module ) and should not be merged until I have provided the rest of the modules hostnamed, timesyncd,resolved etc. ( read as do not enable automerge  ) which will provide the libraries in the existing module.  

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

File: modules.d/02systemd-networkd/module-setup.sh [hunk 1]
```diff
@@ -1,64 +1,79 @@
...
+# Prerequisite check(s) for module.
 check() {
     [[ $mount_needs ]] && return 1
 
+    # If the binary(s) requirements are not fulfilled the module can't be installed
+    require_binaries ip || return 1
+    require_binaries networkctl || return 1
+    require_binaries "$systemdutildir"/systemd-networkd || return 1
+    require_binaries "$systemdutildir"/systemd-network-generator || return 1
+    require_binaries "$systemdutildir"/systemd-networkd-wait-online || return 1
```
Comment (haraldh) [inline modules.d/02systemd-networkd/module-setup.sh:14]:
```suggestion
    require_binaries \
        ip networkctl \
        "$systemdutildir"/systemd-networkd \
        "$systemdutildir"/systemd-network-generator \
        "$systemdutildir"/systemd-networkd-wait-online \
        || return 1
```

**Review by haraldh — CHANGES_REQUESTED** [review]

**Comment by haraldh** [comment]
Would be cool to introduce the test cases like for NM:
```
test/TEST-21-NFS-NM/Makefile
test/TEST-31-ISCSI-NM/Makefile
test/TEST-36-ISCSI-MULTI-NM/Makefile
test/TEST-41-NBD-NM/Makefile
test/TEST-51-MULTINIC-NM/Makefile
test/TEST-61-BONDBRIDGEVLANIFCFG-NM/Makefile
``

with networkd... relevant code changes:

```diff
diff --git a/test/TEST-20-NFS/test.sh b/test/TEST-20-NFS/test.sh
index 5a46f3d5..868f62b8 100755
--- a/test/TEST-20-NFS/test.sh
+++ b/test/TEST-20-NFS/test.sh
@@ -2,10 +2,13 @@
 
 if [[ $NM ]]; then
     USE_NETWORK="network-manager"
-    OMIT_NETWORK="network-legacy"
+    OMIT_NETWORK="network-legacy systemd-networkd"
+elif [[ $SNWD ]]; then
+    USE_NETWORK="systemd-networkd"
+    OMIT_NETWORK="network-legacy network-manager"
 else
     USE_NETWORK="network-legacy"
-    OMIT_NETWORK="network-manager"
+    OMIT_NETWORK="network-manager systemd-networkd"
 fi
```

also for 
```
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh
```

Maybe refactor things into `test/test-functions`

**Comment by johannbg** [comment]
> Would be cool to introduce the test cases like for NM:
> 
> ```
> test/TEST-21-NFS-NM/Makefile
> test/TEST-31-ISCSI-NM/Makefile
> test/TEST-36-ISCSI-MULTI-NM/Makefile
> test/TEST-41-NBD-NM/Makefile
> test/TEST-51-MULTINIC-NM/Makefile
> test/TEST-61-BONDBRIDGEVLANIFCFG-NM/Makefile
> ```
> 
> with networkd... relevant code changes:
> 
> ```diff
> diff --git a/test/TEST-20-NFS/test.sh b/test/TEST-20-NFS/test.sh
> index 5a46f3d5..868f62b8 100755
> --- a/test/TEST-20-NFS/test.sh
> +++ b/test/TEST-20-NFS/test.sh
> @@ -2,10 +2,13 @@
>  
>  if [[ $NM ]]; then
>      USE_NETWORK="network-manager"
> -    OMIT_NETWORK="network-legacy"
> +    OMIT_NETWORK="network-legacy systemd-networkd"
> +elif [[ $SNWD ]]; then
> +    USE_NETWORK="systemd-networkd"
> +    OMIT_NETWORK="network-legacy network-manager"
>  else
>      USE_NETWORK="network-legacy"
> -    OMIT_NETWORK="network-manager"
> +    OMIT_NETWORK="network-manager systemd-networkd"
>  fi
> ```
> 
> also for
> 
> ```
> test/TEST-30-ISCSI/test.sh
> test/TEST-35-ISCSI-MULTI/test.sh
> test/TEST-40-NBD/test.sh
> test/TEST-50-MULTINIC/test.sh
> test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh
> ```
> 
> Maybe refactor things into `test/test-functions`

Create an issue for it and assign it to me I need to take a stab at writing test case :)

**Comment by haraldh** [comment]
> Create an issue for it and assign it to me I need to take a stab at writing test case :)

@johannbg https://github.com/dracutdevs/dracut/issues/1386
