### PR TITLE
fix(dracut.sh): use dynamically uefi's sections offset

### LINKED ISSUE #2275: UKI section offsets are hard-coded
Looking at `dracut.sh` I can see that dracut is still hard-coding PE section offsets despite the warning in v252 release notes. This will cause overlapping PE sections at runtime should the stub's sections grow too much (our ci has been bitten by this, which is why ukify came about). It also fails to mark the `.linux` section as executable (on x86 it may be run in-place if the kernel is too old). Furthermore, a future systemd release may have EFI binaries with a non-zero image base. These hard-coded offsets will result in broken images that will be refused by firmware.

You could fix all this and gain extra features by using ukify, but I guess there is a case of [NIH](https://github.com/dracutdevs/dracut/issues/2191) going on.

### PR DESCRIPTION
**Pull request by keentux**
* Uefi section are creating by `objcopy` with hardcoded sections offset. This patch allow to have a dynamic set of offsets between each part of the efi file, needed to create an UKI. Offsets are simply calculated so no sections overlap, see https://wiki.archlinux.org/title/Unified_kernel_image#Manually
Moreover, efi stub file's header is parsed to apply the correct offsets according to the section alignment factor. More information here: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-windows-specific-fields-image-only
* Remove EFI_SECTION_VMA_INITRD, no need anymore as initrd section offset dynamically calculated.

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #2275

### CODE REVIEW

File: dracut.sh [hunk 1]
```diff
@@ -2467,29 +2464,43 @@ if [[ $uefi == yes ]]; then
         fi
     fi
 
+    offset=$(objdump -h "$uefi_stub" | awk 'NF==7 {size=strtonum("0x"$3);\
```
Comment (aafeijoo-suse) [inline dracut.sh:2467]: Just a minor nitpick, I'd save the output of `objdump -h "$uefi_stub"` to an intermediate variable to check its return code and exit with a dfatal message if it's non-zero.

**Review by aafeijoo-suse — COMMENTED** [review]
Thanks for looking into this!

File: dracut.sh (hunk 1 above)
Comment (keentux) [reply dracut.sh]: Thank you for your feedback.
I add a protection on the result of the command, to be sure that an offset is really taken.

**Comment by medhefgo** [comment]
I forgot to mention that the offsets should really be aligned to the PE binary's SectionAlignment header field.

**Comment by keentux** [comment]
> I forgot to mention that the offsets should really be aligned to the PE binary's SectionAlignment header field.

Thanks for that clarification. I am going to look on at.

**Comment by keentux** [comment]
On my last changes, during the UEFI generation, it will parse the initial PE file's header (the stub) checking if it is a good PE format and catch the value of `sectionAlignment` . According to the PE documentation, each section should start on a factor of the value of `sectionAlignment`. 
@medhefgo What do you think about that. Should it be good up to you ?

File: dracut-functions.sh [hunk 2]
```diff
@@ -1023,3 +1023,24 @@ get_dev_module() {
     fi
     echo "$dev_drivers"
 }
+
+# Check if file is in PE format
+pe_file_format() {
+    if [[ $# -eq 1 ]]; then
+        dos_header=$(hexdump -s 0 -n 64 -e'64/1 "%_c"' "$1")
+        signature=$(hexdump -s 128 -n 4 -e'4 "%_c"' "$1")
```
Comment (medhefgo) [inline dracut-functions.sh:1031]: This is just wrong. The PE header can reside virtually anywhere. You have to examine the offset in the DOS header to find the PE header.
You should build the latest master of systemd to test this as its PE header starts at offset 64 and your code spits out the wrong alignment.

Why not use `objdump -p`? Or better yet: why not just use ukify and get rid of senseless duplication of effort and gain support for more arches in the process?

Comment (keentux) [reply dracut-functions.sh]: Thank you for your feedback, indeed `objdump -p` is cleaner !
Changes applied

File: dracut-functions.sh [hunk 3]
```diff
@@ -1023,3 +1023,25 @@ get_dev_module() {
...
 }
+
+# Check if file is in PE format
+pe_file_format() {
+    if [[ $# -eq 1 ]]; then
+        local magic
+        magic=$(objdump -p "$1" \
+            | awk '{if ($1 == "Magic"){print strtonum("0x"$2)}}')
+        # 0x10b (PE32), 0x20b (PE32+)
+        [[ -n $magic && ($magic == 0x20b || $magic == 0x10b) ]] && return 0
```
Comment (aafeijoo-suse) [inline dracut-functions.sh:1034]: `magic` contains a decimal value and it's being compared to hex values.

`magic=$(printf "0x%x" $magic)` before the check?

Comment (keentux) [reply dracut-functions.sh:1034]: Thanks for this feedback.
Indeed, I thought, in the condition, hexa will be convert in decimal. I am going to update this.

Comment (keentux) [reply dracut-functions.sh]: Perfect! Update done.

**Review by aafeijoo-suse — APPROVED** [review]

**Review by johannbg — APPROVED** [review]
LGTM
