### PR TITLE
fix(bluetooth): dbus configuration path fixes

### LINKED ISSUE #1627: bluetooth: Arch Linux dbus conf path
**Describe the bug**
Arch Linux [bluez](https://archlinux.org/packages/extra/x86_64/bluez/) package is built with [`--with-dbusconfdir=/usr/share`](https://github.com/archlinux/svntogit-packages/blob/bcacf7f904dc526052f14ff798fc206e73343881/trunk/PKGBUILD#L31) but dracut supports config that located only in `/etc`. This leads to an error:
```
dracut-install: ERROR: installing '/etc/dbus-1/system.d/bluetooth.conf'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.QZNJMz/initramfs -a /etc/bluetooth/main.conf /etc/dbus-1/system.d/bluetooth.conf /var/lib/bluetooth/ /var/lib/bluetooth/E0:D4:64:92:20:83 /var/lib/bluetooth/E0:D4:64:92:20:83/F4:73:35:15:0F:53 /var/lib/bluetooth/E0:D4:64:92:20:83/F4:73:35:15:0F:53/info /var/lib/bluetooth/E0:D4:64:92:20:83/cache /var/lib/bluetooth/E0:D4:64:92:20:83/cache/58:20:59:21:66:23 /var/lib/bluetooth/E0:D4:64:92:20:83/cache/C8:47:8C:C3:95:6E /var/lib/bluetooth/E0:D4:64:92:20:83/cache/F4:73:35:15:0F:53 /var/lib/bluetooth/E0:D4:64:92:20:83/settings
```

**Possible fixes**
1. Add support for `/usr/share/dbus-1/system.d/bluetooth.conf` to bluetooth module:
https://github.com/dracutdevs/dracut/blob/f6e6be245d0cda14d90a0442b688c8dca1410a2e/modules.d/62bluetooth/module-setup.sh#L72

2. Add an option to override the path in config.

**Distribution used**
Arch Linux

**Dracut version**
055

**Init system**
systemd

**To Reproduce**
Setup bluetooth keyboard and build initramfs.

**Expected behavior**
`/usr/share/dbus-1/system.d/bluetooth.conf` should be installed to initramfs.

### PR DESCRIPTION
**Pull request by johannbg**
Add a missing /usr/share path ( fixes #1627 )
Use variable instead of hard path

This pull request changes...

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

File: modules.d/62bluetooth/module-setup.sh [hunk 1]
```diff
@@ -69,7 +70,7 @@ install() {
 
         inst_multiple \
             /etc/bluetooth/main.conf \
-            /etc/dbus-1/system.d/bluetooth.conf \
+            "$dbusconfdir"/bluetooth.conf \
```
Comment (aafeijoo-suse) [inline modules.d/62bluetooth/module-setup.sh:73]: `$dbusconfdir` is usually expanded to `/etc/dbus-1`. Shouldn't  [`$dbussystemconfdir`](https://github.com/dracutdevs/dracut/blob/master/dracut.sh#L1643) be here instead?

Comment (johannbg) [reply modules.d/62bluetooth/module-setup.sh]: Spot on Fixed.
